#!/usr/bin/env bash
# bash script that install nginx
sudo apt-get y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
