#!/usr/bin/env bash
# blocks all incoming traffic, except some TCP ports
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming
sudo servi ufw restart
